import { Vollkorn } from "next/font/google";
import "./globals.css";
import Provider from "./provider";

const vollkorn = Vollkorn({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={vollkorn.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
